apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


generatorOptions:
 disableNameSuffixHash: true

commonLabels:
  environment: development

namespace: amq-online-infra

resources:
  - amq-online-backup-job-sa.yaml
  - cluster-role-binding.yaml
  - amq-online-backup-job-pvc.yaml
  - amq-online-backup-cron-job.yaml
#  - amq-online-backup-job.yaml
